export const restaurantsList = [
  {
    id: 1,
    name: 'Miami Subs (167 Street)',
    title:'Featured Establishents',
    offers: 2,
    openingTime: '8am',
    closingTime: '9pm',
    status: 'Featured',
    rating: 4.5,
    image:'',
  },
  {
    id: 2,
    name: 'Pinolandia (Miami)',
    title:'Exclusive for you',
    offers: 0,
    openingTime: '8am',
    closingTime: '9pm',
    status: 'Recommended',
    rating: 4.5,
    image:'',
  },
  {
    id: 3,
    name: 'Miami Grill (Miami Mart)',
    title:'Favourable Establishents',
    offers: 2,
    openingTime: '8am',
    closingTime: '9pm',
    status: 'Local Approved',
    rating: 4.5,
    image:'',
  },
  {
    id: 4,
    name: 'The Taco Stand (Miami)',
    title:'Featured Establishents',
    offers: 2,
    openingTime: '8am',
    closingTime: '9pm',
    status: '',
    rating: 4.5,
    image:'',
  }
]
